# PyTorch Basics and Neural Nets

`PyTorch` is Meta's deep learning framework and is also used for tensor mathematics, taking gradients, etc. It is extremely versatile and a useful alternative to `Tensorflow` and `Keras`.

In this notebook, we will review a few basics of `PyTorch` - detailed examples are available from the site: https://pytorch.org

Installation: https://pytorch.org/get-started/locally/

Quick tutorial: https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html (this is a great and quick read)

In [1]:
from google.colab import drive
drive.mount('/content/drive')  # Add My Drive/<>

import os
os.chdir('drive/My Drive')
os.chdir('Books_Writings/NLPBook/')

Mounted at /content/drive


In [2]:
%%capture

# pylab contains numpy, scipy, and matplotlib
%pylab inline
import pandas as pd
import os

In [3]:
%%capture
# Install if required, and not installed by default, uncomment the line below to install:
# !pip install torch torchvision

In [4]:
import torch

## Tensors

Just as we have numpy arrays, we can also initialize a torch array of any dimension, so it is better to call it a [tensor](https://en.wikipedia.org/wiki/Tensor).  

Here are some basic operations on torch tensors just to get an idea of the syntax. The parallels with [NumPy](https://numpy.org) make this easy.

In [5]:
a = torch.tensor(4)
print(type(a))
print(a+a)

<class 'torch.Tensor'>
tensor(8)


In [6]:
# Casting from ndarry to torch tensor
b = array(8) # numpy array
a = torch.tensor(b)
print(type(a))
print(a+a)

a = torch.from_numpy(b)
print(type(a))
print(a+a)

<class 'torch.Tensor'>
tensor(16)
<class 'torch.Tensor'>
tensor(16)


In [8]:
# Higher dimensions
b = rand(30).reshape((5,2,3))
print(type(b))
print(b.shape)

a = torch.tensor(b)
print(type(a))
print(a)
print(a.shape)

<class 'numpy.ndarray'>
(5, 2, 3)
<class 'torch.Tensor'>
tensor([[[0.3016, 0.2159, 0.9958],
         [0.6859, 0.4305, 0.0250]],

        [[0.2210, 0.7880, 0.1686],
         [0.0166, 0.7800, 0.9184]],

        [[0.0690, 0.8029, 0.0798],
         [0.8117, 0.8787, 0.6555]],

        [[0.3649, 0.5392, 0.2355],
         [0.3020, 0.7983, 0.2249]],

        [[0.0036, 0.5768, 0.2595],
         [0.8700, 0.3191, 0.1916]]], dtype=torch.float64)
torch.Size([5, 2, 3])


In [9]:
# Using random number generators
a = torch.rand((5,2,3))
print(a)

tensor([[[0.5628, 0.9664, 0.1181],
         [0.1249, 0.6062, 0.7248]],

        [[0.9691, 0.3015, 0.8293],
         [0.0977, 0.8317, 0.8576]],

        [[0.8224, 0.5508, 0.0561],
         [0.0924, 0.7842, 0.8844]],

        [[0.1078, 0.3918, 0.5983],
         [0.7696, 0.6157, 0.5451]],

        [[0.4656, 0.6952, 0.0985],
         [0.1794, 0.8737, 0.5431]]])


## Matrix operations

In [11]:
a = [[2.0,3],[1,4]]
b = [[5.0,8]]
c = torch.rand((2,2))
a = torch.tensor(a)
b = torch.tensor(b)
b = torch.t(b)
print(a)
print(b)
print(c)
print(torch.transpose(c,0,1)) # more useful for tensors with more than 2 dimensions

tensor([[2., 3.],
        [1., 4.]])
tensor([[5.],
        [8.]])
tensor([[0.5091, 0.2645],
        [0.3997, 0.0788]])
tensor([[0.5091, 0.3997],
        [0.2645, 0.0788]])


In [12]:
print(torch.transpose(c,1,0))

tensor([[0.5091, 0.3997],
        [0.2645, 0.0788]])


In [13]:
# Addition
print(a+c)
print(torch.add(a,c))

tensor([[2.5091, 3.2645],
        [1.3997, 4.0788]])
tensor([[2.5091, 3.2645],
        [1.3997, 4.0788]])


In [14]:
# Subtraction
print(a-c)
print(torch.sub(a,c))

tensor([[1.4909, 2.7355],
        [0.6003, 3.9212]])
tensor([[1.4909, 2.7355],
        [0.6003, 3.9212]])


In [15]:
# Multiplication
print(a*c) # elementwise
print(torch.mm(a,c)) # matrix multiply
print(torch.mm(a,b)) # notice the transpose required here (not so in numpy)
print(torch.mm(torch.mm(a,c),b))

tensor([[1.0182, 0.7934],
        [0.3997, 0.3152]])
tensor([[2.2174, 0.7653],
        [2.1080, 0.5797]])
tensor([[34.],
        [37.]])
tensor([[17.2097],
        [15.1776]])


In [16]:
# Much easier
a.mm(c).mm(b)

tensor([[17.2097],
        [15.1776]])

## Reshaping and joining tensors

In [17]:
a = torch.rand(4,3)
b = torch.randn(3,4)
print(torch.cat((a,torch.t(b))))
print(torch.cat((a,torch.t(b)),dim=1))

tensor([[ 0.7446,  0.5609,  0.1655],
        [ 0.9341,  0.3611,  0.5136],
        [ 0.0689,  0.1005,  0.6248],
        [ 0.8217,  0.3035,  0.2296],
        [-0.5832, -1.5877,  1.0627],
        [-1.1714, -2.2504, -0.7794],
        [-1.5790,  0.5165, -0.1369],
        [ 1.1054,  1.0551, -1.0913]])
tensor([[ 0.7446,  0.5609,  0.1655, -0.5832, -1.5877,  1.0627],
        [ 0.9341,  0.3611,  0.5136, -1.1714, -2.2504, -0.7794],
        [ 0.0689,  0.1005,  0.6248, -1.5790,  0.5165, -0.1369],
        [ 0.8217,  0.3035,  0.2296,  1.1054,  1.0551, -1.0913]])


In [18]:
torch.reshape(b,(4,3))

tensor([[-0.5832, -1.1714, -1.5790],
        [ 1.1054, -1.5877, -2.2504],
        [ 0.5165,  1.0551,  1.0627],
        [-0.7794, -0.1369, -1.0913]])

## Vector/Matrix Calculus

A look at taking derivatives (gradients).

PyTorch uses automatic differentiation, so if we have a function $f(x)$ where $x$ is a tensor and we designate automatic differentiation for $x$, then PyTorch will keep track of all functions of $x$ (through the computation tree) and also the derivatives of those functions w.r.t. $x$.

Note that if $x$ is a vector of dimension $d$, and $f(x)$ is a scalar function of $x$, then the derivative $\frac{\partial f}{\partial x}$ will be of dimension $d$.

See: https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

Jason Brownlees, [Calculating Derivatives in PyTorch](https://machinelearningmastery.com/calculating-derivatives-in-pytorch/)

In [28]:
%%time
x = torch.tensor([[2.,3.,4.]], requires_grad=True) # make sure this is a matrix [[]]
a = torch.rand((5,3)) # this is automatically a matrix
print("a =", a)
f = torch.mm(a,torch.t(x)).sum() # f is a vector
print("f =", f)

# external_grad = torch.tensor([1., 1., 1.])
# f.backward(gradient=external_grad)
# f.backward() # sum f to get a scalar and then differentiate wrt x, gradients are stored in object x
# print("Gradient =", x.grad) # since there are 3 values in the x vector, we will get 3 derivatives

a = tensor([[0.4906, 0.4870, 0.1294],
        [0.6624, 0.5060, 0.6400],
        [0.3081, 0.1309, 0.5654],
        [0.2462, 0.3671, 0.0800],
        [0.6985, 0.5952, 0.3041]])
f = tensor(17.9462, grad_fn=<SumBackward0>)
CPU times: user 3.79 ms, sys: 0 ns, total: 3.79 ms
Wall time: 3.63 ms


Let's do the same gradient manually and check that we get the same gradients as we obtained from AutoGrad above.

In [29]:
%%time
f.backward() # sum f to get a scalar and then differentiate wrt x, gradients are stored in object x
print("Gradient =", x.grad) # since there are 3 values in the x vector, we will get 3 derivatives

Gradient = tensor([[2.4059, 2.0861, 1.7190]])
CPU times: user 2.34 ms, sys: 98 µs, total: 2.44 ms
Wall time: 3.31 ms


In [30]:
%%time
a1 = a.numpy().copy()
dx = 0.1
for j in range(3):
    x1 = x.detach().numpy().copy() # need to detach gradient vector, and also make a copy, else x will be updated
    x1[0,j] = x1[0,j] + dx
    f1 = a1.dot(x1.T).sum()
    print((f1-f)/dx)

tensor(2.4059, grad_fn=<DivBackward0>)
tensor(2.0861, grad_fn=<DivBackward0>)
tensor(1.7190, grad_fn=<DivBackward0>)
CPU times: user 4.6 ms, sys: 0 ns, total: 4.6 ms
Wall time: 5.3 ms


In [22]:
x = torch.tensor([[2.,3.,4.]], requires_grad=True) # make sure this is a matrix [[]]
a = torch.rand((3,3)) # this is automatically a matrix
print("a =", a)
f = torch.mm(x,torch.mm(a,torch.t(x))) # f is a vector
print("f =", f)

# external_grad = torch.tensor([1., 1., 1.])
# f.backward(gradient=external_grad)
f.backward() # sum f to get a scalar and then differentiate wrt x, gradients are stored in object x
print("Gradient =", x.grad) # since there are 3 values in the x vector, we will get 3 derivatives

a = tensor([[0.8450, 0.4722, 0.6860],
        [0.1778, 0.6785, 0.7844],
        [0.2668, 0.0216, 0.0029]])
f = tensor([[30.7290]], grad_fn=<MmBackward0>)
Gradient = tensor([[9.1414, 8.5952, 4.3474]])


In [23]:
f = torch.mm(torch.mm(x,torch.mm(a,torch.t(x))),torch.mm(x,torch.t(x)))
f.backward()
print("Gradient =", x.grad)

Gradient = tensor([[397.1571, 442.2307, 376.2527]])


In [24]:
# Repeat the example here, but do not sum but keep each element separate with external gradients,
# so f is not needed to be scalar
x = torch.tensor([[2.,3.,4.]], requires_grad=True)
f = torch.mm(a,torch.t(x))
print("f =", f) # f is a vector

external_grad = torch.t(torch.tensor([[1., 1., 1.]]))
f.backward(gradient=external_grad)
# f.sum().backward()
print("Gradient =", x.grad)

f = tensor([[5.8506],
        [5.5290],
        [0.6102]], grad_fn=<MmBackward0>)
Gradient = tensor([[1.2896, 1.1723, 1.4734]])


In [25]:
# Example 1 from PyTorch documentation
a = torch.tensor([2., 3., 5.], requires_grad=True)
b = torch.tensor([6., 4., 2.], requires_grad=True)
Q = 3*a**3 - b**2
print("Q =", Q)
external_grad = torch.tensor([1., 1., 1.])
Q.backward(gradient=external_grad)
# check if collected gradients are correct
print(a.grad, b.grad)
print(9*a**2 == a.grad)
print(-2*b == b.grad)

Q = tensor([-12.,  65., 371.], grad_fn=<SubBackward0>)
tensor([ 36.,  81., 225.]) tensor([-12.,  -8.,  -4.])
tensor([True, True, True])
tensor([True, True, True])


In [26]:
# Example 2 from PyTorch documentation
a = torch.tensor([2., 3., 5.], requires_grad=True)
b = torch.tensor([6., 4., 2.], requires_grad=True)
Q = 3*a**3 - b**2
print(Q)
Q.sum().backward()
# check if collected gradients are correct
print(a.grad, b.grad)
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([-12.,  65., 371.], grad_fn=<SubBackward0>)
tensor([ 36.,  81., 225.]) tensor([-12.,  -8.,  -4.])
tensor([True, True, True])
tensor([True, True, True])


## Reprise of the MNIST digit classification problem

Recall that the MNIST digits occupy a pixel frame of size 28 x 28 = 784 pixels. This is the input size. The labels are digits from 0,1,2,...,9, i.e., a 10-class classification problem.

In [31]:
# importing the libraries
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [32]:
#Sigmoid Function
def sigmoid (x):
    return 1/(1 + torch.exp(-x))

#Derivative of Sigmoid Function/
def derivatives_sigmoid(x):
    return sigmoid(x) * (1 - sigmoid(x))

In [33]:
# Import all the required PyTorch libraries
import torch
import torchvision
import torch.nn as nn
import torchvision.transforms as transforms

In [34]:
# Use a GPU if available, else use a CPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Device =", device)

# Hyper-parameters
input_size = 784
hidden_size = 500 # number of neurons in the hidden layer
num_classes = 10
num_epochs = 5
batch_size = 100
learning_rate = 0.001

# Define a fully connected neural network with one hidden layer
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        # The super() function is used to give access to methods and properties of a parent or sibling class.
        # The super() function returns an object that represents the parent class.
        super(NeuralNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size) # fully connected input and hidden layer 1
        self.relu = nn.ReLU() # type is ReLU
        self.fc2 = nn.Linear(hidden_size, num_classes) # fully connected hidden layer and output layer

    # forward pass that takes input and produces output
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

# Define the model
model = NeuralNet(input_size, hidden_size, num_classes).to(device) # push it to cpu/gpu (using related RAM)

# Loss and optimizer (Adam)
criterion = nn.CrossEntropyLoss() # This will do both softmax and cross-entropy loss in one
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

Device = cpu


In [35]:
# MNIST dataset (images and labels)
train_dataset = torchvision.datasets.MNIST(root='../../data',
                                           train=True,
                                           transform=transforms.ToTensor(),
                                           download=True)

test_dataset = torchvision.datasets.MNIST(root='../../data',
                                          train=False,
                                          transform=transforms.ToTensor())

# Data loader (input pipeline)
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                           batch_size=batch_size,
                                           shuffle=True)

test_loader = torch.utils.data.DataLoader(dataset=test_dataset,
                                          batch_size=10000,
                                          shuffle=False)
print(train_dataset.data.shape)
print(test_dataset.data.shape)

torch.Size([60000, 28, 28])
torch.Size([10000, 28, 28])


In [36]:
%%time
# Train the model
total_step = len(train_loader)
print("Total steps =", total_step)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        # Move tensors to the configured device
        images = images.reshape(-1, 28*28).to(device)
        labels = labels.to(device)

        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)

        # Backward and optimize
        optimizer.zero_grad() # zero out all gradients
        loss.backward() # calculate gradients
        optimizer.step() # update weights

        if (i+1) % batch_size == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))

Total steps = 600
Epoch [1/5], Step [100/600], Loss: 0.3965
Epoch [1/5], Step [200/600], Loss: 0.3846
Epoch [1/5], Step [300/600], Loss: 0.1900
Epoch [1/5], Step [400/600], Loss: 0.1619
Epoch [1/5], Step [500/600], Loss: 0.1939
Epoch [1/5], Step [600/600], Loss: 0.1501
Epoch [2/5], Step [100/600], Loss: 0.2410
Epoch [2/5], Step [200/600], Loss: 0.1240
Epoch [2/5], Step [300/600], Loss: 0.0897
Epoch [2/5], Step [400/600], Loss: 0.0847
Epoch [2/5], Step [500/600], Loss: 0.0989
Epoch [2/5], Step [600/600], Loss: 0.0758
Epoch [3/5], Step [100/600], Loss: 0.0901
Epoch [3/5], Step [200/600], Loss: 0.0648
Epoch [3/5], Step [300/600], Loss: 0.0280
Epoch [3/5], Step [400/600], Loss: 0.1521
Epoch [3/5], Step [500/600], Loss: 0.0247
Epoch [3/5], Step [600/600], Loss: 0.0516
Epoch [4/5], Step [100/600], Loss: 0.0583
Epoch [4/5], Step [200/600], Loss: 0.0593
Epoch [4/5], Step [300/600], Loss: 0.0272
Epoch [4/5], Step [400/600], Loss: 0.0671
Epoch [4/5], Step [500/600], Loss: 0.0455
Epoch [4/5], Ste

In [37]:
%%time
# Test the model
# In test phase, we don't need to compute gradients (for memory efficiency)
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in test_loader:
        images = images.reshape(-1, 28*28).to(device)
        labels = labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print('Accuracy of the network on the 10000 test images: {} %'.format(100 * correct / total))

# Save the model checkpoint
torch.save(model.state_dict(), 'model.ckpt')

Accuracy of the network on the 10000 test images: 97.61 %
CPU times: user 1.53 s, sys: 87.6 ms, total: 1.62 s
Wall time: 2.12 s


In [38]:
confusion_matrix(predicted, labels)

array([[ 960,    0,    4,    0,    0,    2,    3,    1,    0,    1],
       [   0, 1124,    2,    0,    0,    0,    3,    2,    0,    3],
       [   4,    2, 1005,    4,    3,    0,    0,   10,    2,    0],
       [   2,    3,    4,  998,    1,   19,    2,    4,   21,    6],
       [   1,    0,    2,    0,  957,    1,    3,    0,    3,    8],
       [   1,    1,    0,    1,    0,  860,    8,    0,    4,    0],
       [   2,    1,    1,    0,    2,    2,  933,    0,    1,    0],
       [   3,    0,    5,    2,    2,    1,    0,  998,    3,    2],
       [   4,    4,    9,    2,    0,    4,    6,    3,  937,    0],
       [   3,    0,    0,    3,   17,    3,    0,   10,    3,  989]])

In [39]:
print(classification_report(predicted, labels))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       971
           1       0.99      0.99      0.99      1134
           2       0.97      0.98      0.97      1030
           3       0.99      0.94      0.96      1060
           4       0.97      0.98      0.98       975
           5       0.96      0.98      0.97       875
           6       0.97      0.99      0.98       942
           7       0.97      0.98      0.98      1016
           8       0.96      0.97      0.96       969
           9       0.98      0.96      0.97      1028

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000



How will you use the code above for text classification?